create sequence IF NOT EXISTS GATEWAY_SEQ  START WITH 1 INCREMENT BY 1;
create sequence IF NOT EXISTS PERIPHERAL_SEQ START WITH 1 INCREMENT BY 1;

create table IF NOT EXISTS GATEWAY
(
  ID                 INTEGER default NEXT VALUE FOR "PUBLIC"."GATEWAY_SEQ"
    primary key,
  SERIAL_NUMBER      VARCHAR_IGNORECASE
    constraint GATEWAY_SERIAL_NUMBER_UINDEX
    unique,
  HUMAN_READABLE_NAME VARCHAR_IGNORECASE,
  IP_V4              VARCHAR_IGNORECASE
);

create table IF NOT EXISTS PERIPHERAL
(
  ID           INTEGER default NEXT VALUE FOR "PUBLIC"."PERIPHERAL_SEQ"
    primary key,
  UID          NUMERIC,
  CREATED_DATE DATE(10),
  STATUS       BOOLEAN,
  GATEWAY_ID   INTEGER,
  VENDOR       VARCHAR_IGNORECASE,
  constraint GATEWAY_ID_FK
  foreign key (GATEWAY_ID) references GATEWAY
);

